apiVersion: v1
kind: Pod
metadata:
  name: nginx-startup-only
  labels:
    app: my-app-np
spec:
  containers:
  - name: nginx
    image: nginx:latest
    command: ["sh", "-c", "sleep 40 && nginx -g 'daemon off;'"]
    ports:
    - containerPort: 80
    startupProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 10    # allow 10 failures
      periodSeconds: 5 
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: my-app-np
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
